module.exports = [
  'Why so serious?',
  'Not clown - Joker',
  'I used to think my life was a tragedy, but now I realize it’s a comedy.',
  'What doesn’t kill you simply makes you stranger!',
  'When I saw what a black, awful joke the world was, I went crazy as a coot!',
  'As you know, madness is like gravity: All it takes is a little push.',
  'If you’re good at something, never do it for free.',
  'When the chips are down, these civilized people, they’ll eat each other.',
  'The only sensible way to live in this world is without rules.',
  'Their morals, their code—it’s a bad joke.',
  'When they treat you like a joke, leave them like it’s funny.',
  'Is it just me or is it getting crazier out there?',
  'You have nothing, nothing to threaten me with. Nothing to do with all your strength.',
  'It’s funny. When I was a little boy and told people I was going to be a comedian, everyone laughed at me. Well, no one’s laughing now!',
  'It’s not about the money, it’s about sending a message.',
  'You know, it only hurts when I laugh.',
  'They need you right now, but when they don’t, they’ll cast you out like a leper.',
  'Don’t test the monster in me!',
  'I’m not good at future planning. I do not plan at all. Don’t know what I’m doing tomorrow. Do not have a day planner and don’t have a diary. I completely live in the now, not in the past, not in the future.',
  'Does it depress you to know just how alone you really are?',
  'Why don’t you just give me a call when you start taking things a little more seriously?',
  'I don’t know why everyone is so rude, I don’t know why you are; I don’t want anything from you.',
  '‎Introduce a little anarchy. Upset the established order, and everything becomes chaos. I’m an agent of chaos.',
  'You know, you remind me of my father. I hated my father.',
  'Do you want to know why I use a knife? Guns are too quick.',
  'I’m a dog chasing cars. I wouldn’t know what to do with one if I caught it.',
  'I feel like I know you. I’ve been watching you forever.',
  'Kid, I’m the Joker. I don’t just randomly kill people. I kill people when it’s funny.',
  'For my whole life, I didn’t know if I even really existed. But I do, and people are starting to notice.',
  'Do I look like the kind of clown that can start a movement?',
  'A man with nothing to fear is a man with nothing to love.',
  'The worst part of having a mental illness is people expect you to behave as if you don’t.',
  'All I have are negative thoughts.',
  'I’m not political. I’m just trying to make people laugh.',
  'You actually believed that all it would take is a few chemicals, a couple of days in drug-induced isolation and a cheap little nervous breakdown and you’d have me all figured out? Like there was some rabbit hole you could follow me down to understanding?',
  'You think men like Thomas Wayne ever think what it’s like to be someone like me? To be somebody but themselves? They don’t. They think that we’ll just sit there and take it, like good little boys! That we won’t werewolf and go wild!',
  'You really want to know what it feels like to be the clown at midnight? Where there’s only ever one joke and it’s always on you? Well, here you are. Now do you get it?',
  'What do you get when you cross a mentally ill loner with a society who abandons him and treats him like trash? You get what you fucking deserve!',
  'My mother always tells me to smile and put on a happy face. She told me I had a purpose to bring laughter and joy to the world.',
  'Everybody just yells and screams at each other. Nobody’s civil anymore. Nobody thinks what it’s like to be the other guy.',
  'I hope my death makes more sense than my life.',
  'Do I look like I’m joking?',
  'In my dream, the world had suffered a terrible disaster. A black haze shut out the sun, and the darkness was alive with the moans and screams of wounded people. Suddenly, a small light glowed. A candle flickered into life, symbol of hope for millions. A single tiny candle, shining in the ugly dark. I laughed and blew it out.',
  'It’s a funny world we live in.',
  'A bit of advice…don’t ever apologize to no one for the way you look.',
  'Forgive my laughter. I have a condition.',
  'Comedy is subjective, Murray. Isn’t that what they say? All of you, the system that knows so much, you decide what’s right or wrong. The same way that you decide what’s funny or not.',
  'Let’s put a smile on that face!',
  'You see, I’m not a monster. I’m just ahead of the curve.',
  'Now, I see the funny side. Now I’m always smiling.',
  'I’ve been using it as a journal, but also as a joke diary, if I have any thoughts or frustrations. I think I told you, I’m pursuing a career in standup comedy.',
  'Nobody panics when things go ‘according to plan,’ even if the plan is horrifying.',
  'No matter the situation, always wear a smile.',
  'Do you know how I got these scars?',
  "All it takes is one bad day to reduce the sanest man alive to lunacy. That's how far the world is from where I am. Just one bad day.",
  "Fool you once, shame on you. Fool you twice, Joker's Trick...",
];
